# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Solitude
subtitle: 'ä¸€ä¸ªç®€æ´ä¼˜é›…çš„ Hexo ä¸»é¢˜'
description: ä¸€ä¸ªç®€æ´ä¼˜é›…çš„ Hexo ä¸»é¢˜ï¼Œæ”¯æŒæ‡’åŠ è½½ã€PWAã€Latex å’Œå¤šç§è¯„è®ºç³»ç»Ÿã€‚
keywords: 'Ever Fu,Solitude'
author: Ever Fu
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://solitude.js.org/preview/zh
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: preview-zh
public_dir: docs/.vitepress/dist/preview/zh/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:
  - preview/zh

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: solitude
theme_config:
  site:
    name:
      class: text
      custom: Solitude
    # ç½‘é¡µicon
    # Web icon
    icon: https://s3.qjqq.cn/47/66c2b219a226f.png!color

  nav:
    menu:
      æ–‡åº“: # æ˜¾ç¤ºåç§° / Display name
        å½’æ¡£: /archives/ || fas fa-folder-closed # å­èœå•åç§°ï¼šè·¯å¾„ || å›¾æ ‡ / Submenu name: path || icon
        åˆ†ç±»: /categories/ || fas fa-clone
        æ ‡ç­¾: /tags/ || fas fa-tags
      å‹é“¾:
        å‹æƒ…é“¾æ¥: /links/ || fas fa-user-group
        å®è—åšä¸»: javascript:travelling() || fas fa-gift
      å…³äº: /about/

    right:
      random: true # éšæœºæ–‡ç« è·³è½¬ / random post button
      custom:
        - name: English
          url: /
          icon: fas fa-language

  hometop:
    enable: true # æ˜¯å¦æ‰“å¼€ / if enable
    # banner display
    banner:
      # å·¦ä¸Šè§’æ˜¾ç¤ºå¤§æ–‡å­—
      # Large text displayed in the upper left corner
      # tipï¼šå¯ä½¿ç”¨htmlæ ‡ç­¾
      # tip: html tags be used
      title: å®é™è‡´è¿œ <br>çƒ­çˆ±ç”Ÿæ´»
      # å·¦ä¸Šè§’æ˜¾ç¤ºå°æ–‡å­—
      # Small text displayed in the upper left corner
      url: Hexo Theme Solitude
      # è½®æ’­icon
      # Carousel icon
      # tip: 76x76 size
      icon:
        HTML: # åå­— / Name
          img: https://s3.qjqq.cn/47/66c2a95ed3cb3.png!color # å›¾ç‰‡ / Image
          color: "#E14E1D" # èƒŒæ™¯è‰² / Background color
        JS:
          img: https://s3.qjqq.cn/47/66c2a97c62826.png!color
          color: "#F0DB50"
        Docker:
          img: https://s3.qjqq.cn/47/66c2a9a40c1c7.png!color
          color: "#2496EE"
        Flutter:
          img: https://s3.qjqq.cn/47/66c2a9c318057.png!color
          color: "#252938"
        WebPack:
          img: https://s3.qjqq.cn/47/66c2a9e5ecfb4.png!color
          color: "#252938"
        Git:
          img: https://s3.qjqq.cn/47/66c2aa0398240.png!color
          color: "#F13C2E"

    # å·¦ä¸‹è·³è½¬æŒ‰é’®
    # Banner lower left jump button
    group:
      Course: /categories/æ•™ç¨‹/ || fas fa-book || linear-gradient(to right,#358bff,#15c6ff)

    # å³ä¾§ç½®é¡¶åˆ—è¡¨ï¼ˆåœ¨æ–‡ç« çš„front matterä¸­æ·»åŠ â€œrecommend: trueâ€ï¼‰
    # Right top list (add "recommend: true" in the front matter of the article)
    recommendList:
      # å·¦ä¸Šè§’æ˜¾ç¤ºæ–‡å­—
      # Large text displayed in the upper left corner
      sup: Top
      # å·¦ä¸‹è§’å¤§å­—
      # Large text in the lower left corner
      title: Solitude æ–‡æ¡£
      # ç‚¹å‡»è·³è½¬é“¾æ¥
      # Click the jump link
      url: https://solitude.js.org/
      # æ˜¾ç¤ºèƒŒæ™¯å›¾ç‰‡
      # Display background image
      img: https://s3.qjqq.cn/47/66c2b25979b09.png!color
      # é˜´å½±é¢œè‰²
      # Shadow color
      color: "none"

  aside:
    home:
      noSticky: "about"
      Sticky: "allInfo"
    post:
      noSticky: "about"
      Sticky: "newestPost"
    page:
      noSticky: "about"
      Sticky: "newestPost,allInfo"
    position: 1
    card:
      style: 1
      author:
        img: https://github.com/everfu.png
        sticker:
      url: /about/
      content: Share new knowledge and record the moments of life.
      content2: This site is powered by Hexo and has the theme of Solitude.
      sayhello: # æ ·å¼ä¸º2æ—¶æ— æ•ˆ
        morning: âœ¨ Good morning. It's a new day
        noon: It's time for a midday break
        afternoon: Tea time. ğŸµ
        night: early bedtime
        goodnight: Good night ğŸ˜´
      sayhello2: # æ ·å¼ä¸º2æ—¶æ— æ•ˆ
        - You'll make it.
        - You're gonna make it.
        - Good luck, stranger.
      information: # æ ·å¼ä¸º1æ—¶è¯·ä¸è¦è¶…è¿‡4ä¸ª
        Github: https://github.com/everfu || fab fa-github
        Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili

    toc:
      post: true
      page: false
      vague: true

    tags:
      enable: true
      limit: 20
      highlight_list:
      #  - Hexo

    archive:
      enable: true
      # æ˜¾ç¤ºç±»å‹
      type: "month" # month: æŒ‰æœˆ / year: æŒ‰å¹´ : month: by month / year: by year

    # å»ºç«™ä¿¡æ¯
    # Website information
    siteinfo:
      # æ–‡ç« æ•°
      # Number of articles
      postcount: true
      # æ€»å­—æ•°
      # The number of words on the web site
      wordcount: true
      # è®¿é—®é‡
      # PV
      pv: true
      # è®¿å®¢æ•°
      # UV
      uv: true
      # æœ€åæ›´æ–°æ—¥æœŸ
      # Last update date
      updatetime: false
      # å»ºç«™æ—¶é—´
      # Website creation time
      runtimeenable: true
      # æ ¼å¼ï¼šyyyy-MM-dd hh-mm-ss
      # Format: yyyy-MM-dd hh-mm-ss
      runtime: "2023-04-20 00:00:00"

  # é¦–é¡µæ–‡ç« é…ç½®ä¿¡æ¯
  # Configure information on the home page
  index_post_list:
    direction: row # row / column
    column: 2 #2:2åˆ— 3:3åˆ—
    content: 2 # 1: post.description / 2: è‡ªåŠ¨è·å–descriptionæˆ–æˆªå–å†…å®¹(Automatically get descriptions or screenshots) / 3: åªä½¿ç”¨æˆªå–å†…å®¹(Use only screenshots) / false: ä¸æ˜¾ç¤ºå†…å®¹(No content is displayed)
    length: 200 # æˆªå–å†…å®¹çš„é•¿åº¦ : The length of the screenshot content
    cover: both # left: åœ¨å·¦ä¾§ : left / right: åœ¨å³ä¾§ : right / both: ä¸¤ä¾§ : both

  # é¡µé¢é»˜è®¤è®¾ç½®
  # page default settings
  page:
    error: true # 404é¡µé¢ / 404 page
    tags: true # æ ‡ç­¾é¡µ /  Tags page
    categories: true # åˆ†ç±»é¡µ /  Categories page
    default: # é»˜è®¤å€¼ /  Default value
      # é»˜è®¤å›¾ç‰‡
      # default cover
      cover:
      # - /img/default.avif # é»˜è®¤å›¾ç‰‡ / default cover

  says:
    enable: true
    home_mini: true
    style: 1
    strip: 30

  # æ–‡ç« é¡µé»˜è®¤è®¾ç½®
  # post default settings
  post:
    default:
      # æ–‡ç« é»˜è®¤å›¾ç‰‡
      # default cover
      cover:
      # -  # é»˜è®¤å›¾ç‰‡ / default cover
      # æ–‡ç« å‘å¸ƒé»˜è®¤åœ°å€
      # default post locate
      locate: China
      # æ–‡ç« é»˜è®¤ç‰ˆæƒ
      # default post copyright
      copyright:
        enable: true
        author:
          url: /about/ # ç‚¹å‡»å¤´åƒè·³è½¬åœ°å€
          img: # æ˜¾ç¤ºå¤´åƒï¼Œä¸å¡«å†™é»˜è®¤æ˜¾ç¤ºsite_icon
        license: CC BY-NC-SA 4.0
        licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
    # é¡¶éƒ¨æ–‡ç« ç®€ä»‹
    # Top article introduction
    meta:
      date: true # å‘å¸ƒæ—¥æœŸ / Release date
      updated: true # æ›´æ–°æ—¥æœŸ / Update date
      locate: false # ä½ç½® / Location
      wordcount: true # å­—æ•° / Number of words
      readtime: true # è®¿é—® / uv
      pv: true # æµè§ˆé‡ / pv
      comment: false # è¯„è®ºæ•° / Comment count
    # æ‰“èµ
    # reward
    award:
      enable: true
      appreciators: /about # èµèµè®°å½• / Appreciative records
      title: æ„Ÿè°¢æ‚¨çš„èµèµ
      desc: å› ä¸ºæ‚¨çš„æ”¯æŒï¼Œæˆ‘æ‰æ„è¯†åˆ°å†™æ–‡ç« çš„ä»·å€¼
      list:
        - name: å¾®ä¿¡
          qcode: https://s3.qjqq.cn/47/66c2b322adbd3.png!color
          url: https://s3.qjqq.cn/47/66c2b322adbd3.png!color
          color: "#7bbd3f"
        - name: æ”¯ä»˜å®
          qcode: https://s3.qjqq.cn/47/66c2b37d1aa6e.png!color
          url: https://s3.qjqq.cn/47/66c2b37d1aa6e.png!color
          color: "#1C8BFF"
    # åˆ†äº«æŒ‰é’®ï¼Œéœ€è¦æ˜¯ä»€ä¹ˆå“ªäº›æŒ‰é’®ï¼Œå¡«å†™åå¼€å¯
    share:
      enable: true
      list:
        - qq
        - weibo
        - twitter
        - facebook
        - telegram
        - whatsapp
        - linkedin
        - link
        - qrcode
    # ç‰ˆæƒä¸­è®¢é˜…æŒ‰é’®è·³è½¬é“¾æ¥ï¼Œå¡«å†™åœ°å€åå¼€å¯
    # Subscription button jump link in copyright
    rss: /atom.xml
    covercolor:
      enable: true
      mode: api # localï¼šæœ¬åœ°å–è‰² / apiï¼šimg2colorå–è‰² : local: local color / api: img2color color
      api: https://img2color-efu.vercel.app/api?img= # apiåœ°å€ / api address
      time: 43200000 # apiå–è‰²é—´éš”ï¼ˆæ¯«ç§’ï¼‰ï¼Œé»˜è®¤ä¸º12å°æ—¶ / api color interval (milliseconds), default is 12 hours
    footer:
      enable: true
      desc: From Ever Fu's article.
      button: # è·³è½¬æŒ‰é’®
        enable: false
        name: More
        url: /about/

  # Custom Theme Color
  theme_color:
    dark: "#8f4dcc" # Dark mode
    dark_op: "#f2b94b23" # Dark mode transparent
    dark_op_deep: "#f2b94bdd" # Dark mode transparent dark
    dark_none: "#f2b94b00" # Dark mode transparent colorless
    light: "#425AEF" # Light mode
    light_op: "#4259ef23" # Light mode transparent
    light_op_deep: "#4259efdd" # Light mode transparent dark
    light_none: "#4259ef01" # Light mode transparent colorless

  display_mode:
    type: auto
    universe: true

  footer:
    information:
      author: false
      left:
        Github: https://github.com/everfu || fab fa-github
        Email: mailto:o@efu.me || fas fa-envelope
      right:
        Bilibili: https://space.bilibili.com/1329819902 ||  fab fa-bilibili
        Douyin: https://v.douyin.com/iJsLc8jt/ || fab fa-tiktok

    group:
      Project:
        Document: https://solitude.js.org
        Github: https://github.com/everfu/hexo-theme-solitude
      Sponsor:
        Patreon: https://www.patreon.com/everfu
        Polar: https://polar.sh/everfu
    randomlink: true
    links:
      - name: Theme
        url: https://github.com/everfu/hexo-theme-solitude
      - name: RSS
        url: /atom.xml

  errorpage:
    img: /img/404.avif
    text: 404 Not Found
    recommendList: true

  copy:
    enable: true
    copyright:
      enable: false
      limit: 50 # word count. ï¼ˆå­—æ•°ï¼‰

  # æ‡’åŠ è½½
  # lazyload
  lazyload:
    enable: true
    field: site # post, site
    placeholder: /img/loading.avif
    errorimg: /img/error_load.avif

  loading:
    fullpage: true
    pace: true

  highlight:
    enable: true
    limit: 200 # ä»£ç è¡Œé«˜é™åˆ¶ / Code line limit
    copy: true # æ˜¯å¦å¼€å¯å¤åˆ¶æŒ‰é’® / Whether to enable the copy button
    expand: true # æ˜¯å¦é»˜è®¤å±•å¼€ / Whether to expand by default
    theme: mac # default: é»˜è®¤ / mac : apple terminal
    color: default # default: é»˜è®¤  / solidity: solidity / dracula: dracula

  lightbox: true
  fancybox: true
  mediumZoom: false

  mermaid: true

  OpenGraph:
    enable: true
    options:
    #  twitter_card:
    #  twitter_image:
    #  twitter_id:
    #  twitter_site:
    #  google_plus:
    #  fb_admins:
    #  fb_app_id:

  wordcount: true
  busuanzi: true
  busuanzi_use: 0 # 0: åŸç‰ˆ / 1: é’ç§¸(other: å…¶å®ƒè‡ªå®šç¾©çš„busuanziå¹³å°)

  search:
    enable: true
    type: local
    tags:
      - Solitude
    algolia:
    # hits:
    #   per_page: 6
    local:
      preload: false
      CDN: /preview/zh/search.xml

  katex:
    enable: true
    per_page: true # æ˜¯å¦åœ¨æ¯é¡µéƒ½åŠ è½½ / Whether to load on each page
    copytex: true # æ˜¯å¦å¼€å¯å¤åˆ¶å…¬å¼ / Whether to enable copy formula

  console:
    enable: true
    recentComment:
      enable: true
      storage: .2
    card:
      tags: true
      archive: true

  extends:
    head: # åœ¨headä¸­æ’å…¥ / Insert in head
    # - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
    body: # åœ¨bodyä¸­æ’å…¥ / Insert in body

  pwa:
    enable: false
    manifest: /manifest.json # manifest.json æ–‡ä»¶è·¯å¾„
    theme_color: "#006a73" # ä¸»é¢˜é¢œè‰²
    mask_icon: /img/pwa/favicon.ico # é®ç½©å›¾æ ‡
    apple_touch_icon: /img/pwa/favicon.ico # è‹¹æœè§¦æ‘¸å›¾æ ‡
    bookmark_icon: /img/pwa/favicon.ico # ä¹¦ç­¾å›¾æ ‡
    favicon_32_32: /img/pwa/favicon_32.ico # 32x32å›¾æ ‡
    favicon_16_16: /img/pwa/favicon_16.ico # 16x16å›¾æ ‡

  #background:
  #  enable: true
  #  opacity: .2
  #  dark: https://i.pinimg.com/originals/d8/b3/9d/d8b39d12b653810db452c437211aeb2e.png
  #  light: https://i.pinimg.com/originals/93/57/38/935738ed9657b296c2ef0ebd2151eb66.jpg

  right_menu:
    enable: true
    custom_list:
      - name: Random
        click: toRandomPost()
        id: menu-randomPost
        class:
        icon: fas fa-random
      - name: Categories
        click: pjax.loadUrl('/categories/') # å¤–é“¾ç”¨ window.openï¼Œpjax æ— æ³•è¯·æ±‚è·¨åŸŸå†…å®¹
        id:
        class:
        icon: fas fa-clone
      - name: Tags
        click: pjax.loadUrl('/tags/')
        id:
        class:
        icon: fas fa-tags

  expire:
    enable: true
    time: 30 # days
    position: top # top / bottom
    text_prev: 'è¿™ç¯‡æ–‡ç« å·²ç»è¿‡æœŸ'
    text_next: 'ï¼Œå¦‚æœå†…å®¹ä¸ç¬¦ï¼Œè¯·è”ç³»æˆ‘'

  CDN:
    internal: custom
    third_party: custom
    version: true
    custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
    option:
      busuanzi_js: https://vercount.one/js

# abbrlink config
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex        #support dec(default) and hex
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default)
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
    enable: true  #true(default)
    depth:        #3(default)
    over_write: false
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink. This only updates abbrlink rather than other front variables.

search:
  path: search.xml
  field: post
  content: true
  format: html

nofollow:
  enable: true
  field: site
  exclude:
    - 'exclude1.com'
    - 'exclude2.com'
